
services:
  web:
    image: nginx
    container_name: day37-web
    ports:
      - "${PORT}:80"
    restart: always
    environment:
      APP_ENV: "${APP_ENV}"
      COMPANY: "${xyz pvt ltd}"
       VERSION: "v2-feature-login"
